extern  printf
extern  GetModuleHandleA
extern  LoadIconA
extern  LoadCursorA
extern  RegisterClassA
extern  DefWindowProcA
extern  GetLastError
extern  CreateWindowExA
extern  ShowWindow
extern  D2D1CreateFactory
extern  GetClientRect
extern  ValidateRect
extern  PostQuitMessage
extern  PeekMessageA
extern  TranslateMessage
extern  DispatchMessageA
extern  DWriteCreateFactory
extern  GetUserDefaultLocaleName
extern  __mingw_swprintf
; Winsocks
    extern  WSAStartup
    extern  getaddrinfo
    extern  socket
    extern  bind
    extern freeaddrinfo