; MSVCRT
    extern  printf
    extern  __mingw_swprintf
; Win32
    extern  GetModuleHandleA
    extern  LoadIconA
    extern  LoadCursorA
    extern  RegisterClassA
    extern  DefWindowProcA
    extern  GetLastError
    extern  CreateWindowExA
    extern  ShowWindow
    extern  GetClientRect
    extern  ValidateRect
    extern  PostQuitMessage
    extern  PeekMessageA
    extern  TranslateMessage
    extern  DispatchMessageA
    extern  GetUserDefaultLocaleName
    extern  MessageBoxA
; Direct2D
    extern  D2D1CreateFactory
; DirectWrite
    extern  DWriteCreateFactory
; Winsocks
    extern  WSAStartup
    extern  getaddrinfo
    extern  socket
    extern  bind
    extern  freeaddrinfo
    extern  WSACleanup
    extern  WSAGetLastError
    extern  closesocket